// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.patch').default>>>>
    }
    '/api/appointments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/appointments.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/appointments.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-request.post').default>>>>
    }
    '/api/auth/reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset.post').default>>>>
    }
    '/api/doctors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/doctors.get').default>>>>
    }
    '/api/fhir/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fhir/import.post').default>>>>
    }
    '/api/labs/file': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labs/file.get').default>>>>
    }
    '/api/labs/upload-xml': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labs/upload-xml.post').default>>>>
    }
    '/api/labs/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/labs/upload.post').default>>>>
    }
    '/api/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.post').default>>>>
    }
    '/api/patients/:id/appointments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patients/[id]/appointments.get').default>>>>
    }
    '/api/patients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patients/index.get').default>>>>
    }
    '/api/prescriptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prescriptions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prescriptions.post').default>>>>
    }
    '/api/profile': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile.patch').default>>>>
    }
    '/api/records/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/[id].get').default>>>>
    }
    '/api/records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/index.get').default>>>>
    }
    '/api/reminders/preview': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/preview.post').default>>>>
    }
    '/api/render-html': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/render-html.get').default>>>>
    }
    '/api/settings': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings.patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}